version: '3'

services: 

  converterapi:
    build: converterAPI/
    restart: on-failure
    ports:
      - 8087:5000

  flaskapp:
    build: FlasklApp/
    restart: on-failure
    ports:
      - 5000:5000
    links:
      - converterapi
 

    

