version: '3'

services: 

  converterAPI:
    build: converterAPI/
    restart: always
    ports:
      - 3000:3000

  FlasklApp:
    build: FlasklApp/
    restart: always
    ports:
      - 5000:5000
 

    

